spring:
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/testdb'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: somepassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  profiles:
    active: dev

  security:
    jwt-secret: AAAAAAAAAAAAAAAAAAAAAAAAADSFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    oauth2:
      client:
        registration:
          google:
            client-id: ASDF
            client-secret: ASDF
            redirect-uri: '{baseUrl}/api/oauth2/callback/{registrationId}'
            scope:
              - email
              - profile
          naver:
            client-id: ASDF
            client-secret: ASDF
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/api/oauth2/callback/{registrationId}'
          kakao:
            client-id: ASDF
            client-secret: ASDF
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/api/oauth2/callback/{registrationId}'
            client-name: kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


#cache: # Use if we implement Caffeine caching
#  expire-after-write: 1m
#  maximum-size: 100


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    oauth2RedirectUrl: '/api/oauth2/callback/google'
    oauth:
      use-pkce-with-authorization-code-grant: true
