name: CI Pipeline  # 워크플로우 이름

on:
  push:
    branches:
      - 'feat/*'  # feat/* 브랜치에 push 시 실행
      - 'dev'
  pull_request:
    branches:
      - dev  # dev 브랜치로 PR 생성 시 실행
      - main  # main 브랜치로 PR 생성 시 실행

jobs:
  build-and-test:  # Job 이름
    runs-on: ubuntu-latest  # 작업 실행 환경

    services:
      db:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: somepassword
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=somepassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code  # Step 이름
        uses: actions/checkout@v2  # GitHub Action 사용 (코드 체크아웃)

      - name: Set up Eclipse Temurin JDK 17  # Eclipse Temurin JDK 설정
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Lint Check  # 린트 체크 실행
        run: ./gradlew ktlintCheck

      - name: Build with Gradle  # Gradle 빌드 실행
        run: ./gradlew build
