name: CI Pipeline  # 워크플로우 이름

on:
  push:
    branches:
      - 'feat/*'  # feat/* 브랜치에 push 시 실행
  pull_request:
    branches:
      - dev  # dev 브랜치로 PR 생성 시 실행
      - main  # main 브랜치로 PR 생성 시 실행

jobs:
  build-and-test:  # Job 이름
    runs-on: ubuntu-latest  # 작업 실행 환경

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: yourpassword
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=yourpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code  # Step 이름
        uses: actions/checkout@v2  # GitHub Action 사용 (코드 체크아웃)

      - name: Set up Eclipse Temurin JDK 17  # Eclipse Temurin JDK 설정
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up application.properties
        run: |
          mkdir -p ./src/main/resources
          touch ./src/main/resources/application.properties
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties

      - name: Lint Check  # 린트 체크 실행
        run: ./gradlew ktlintCheck

      - name: Build with Gradle  # Gradle 빌드 실행
        run: ./gradlew build -x test

      - name: Setup MySQL
        run: docker compose -f docker-compose.yaml up -d

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h 127.0.0.1 -u root --password=yourpassword --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Run Tests  # 테스트 실행
        run: ./gradlew test
